/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "JniUtil.h"
#include "QdiamMDClient.h"
#include "QdiamMDHandler.h"
#include "QdamFtdcMdApi.h"
#include "QdamFtdcUserApiDataType.h"
#include "QdamFtdcUserApiStruct.h"
/* Header for class com_quantdo_qdiammd_jni_QdiamJniTemplate */

#ifndef _Included_com_quantdo_qdiammd_jni_QdiamMDJniTemplate
#define _Included_com_quantdo_qdiammd_jni_QdiamMDJniTemplate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_quantdo_qdiammd_jni_QdiamJniTemplate
 * Method:    ncMdInit
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_quantdo_qdiammd_jni_QdiamMDJniTemplate_ncMdInit
  (JNIEnv *, jclass, jstring, jstring,jint);

/*
 * Class:     com_quantdo_qdiammd_jni_QdiamJniTemplate
 * Method:    ncMdDestory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_quantdo_qdiammd_jni_QdiamMDJniTemplate_ncMdDestory
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
