/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_quantdo_trader_jni_TraderJniTemplate */

#ifndef _Included_com_quantdo_trader_jni_TraderJniTemplate
#define _Included_com_quantdo_trader_jni_TraderJniTemplate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_quantdo_trader_jni_TraderJniTemplate
 * Method:    ncTraderInit
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_quantdo_trader_jni_TraderJniTemplate_ncTraderInit
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     com_quantdo_trader_jni_TraderJniTemplate
 * Method:    ncTraderDestory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_quantdo_trader_jni_TraderJniTemplate_ncTraderDestory
  (JNIEnv *, jclass);

/*
 * Class:     com_quantdo_trader_jni_TraderJniTemplate
 * Method:    ncReq
 * Signature: (Ljava/lang/String;Ljava/util/Map;I)V
 */
JNIEXPORT void JNICALL Java_com_quantdo_trader_jni_TraderJniTemplate_ncReq
  (JNIEnv *, jobject, jstring, jobject, jint);

/*
 * Class:     com_quantdo_trader_jni_TraderJniTemplate
 * Method:    ncNextOrderLocalID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_quantdo_trader_jni_TraderJniTemplate_ncNextOrderLocalID
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
